### ISSUE TITLE
Issue with running the project

### ISSUE THREAD

**Issue by lesenelir** [childrentime/pareto#1]
Hey childrentime, I tried running the project located in `/examples/base`, but it seems that I couldn't get it work. I'm not sure if I'm launching it incorrectly.

Here's how I  started the project:

- In the `/pareto`, `pnpm i`
- In the `/examples/base`, `pnpm dev`

When I visit `localhost:4000`, the project doesn't start.  Could you please confirm whether I have started the project correctly, or if the project is still under development?

**Comment by childrentime** [comment]
sorry. please visit `localhost:4000/home` because it need to map routes.

**Comment by childrentime** [comment]
The project is under devoplopment. I have some changes in local.  However, I've been quite busy with work recently. As soon as I get a bit of free time, I will push again.

**Comment by lesenelir** [comment]
I get it now. Thanks for explaining!
