### ISSUE TITLE
bug：start failed under windows environment

### ISSUE THREAD

**Issue by Giuliao** [childrentime/pareto#5]
## Description

While i start pareto project under windows environment  and access http://localhost:4000/ the app broken.

## Why the error
I have checked the code. I found the path writing to the file will be like,
```
D:\test
```
Yes, nodejs have rightly parsed the path 'D:\\test'  when output it to the console or file. But the comiler read path from files will be  broken. Because the slash will escape the character 't'. The \t will be explained to 'tab'.

## Solution

i have tried fixed it by writing a function to transform the path with double '\\\\' under window environment.
```js
const os = require("os");
/**
 * Transform the OS path separator in the content based on the platform, while writing to files.
 * in windows the path should be replaced with \\ in files, for example, "D:\\test"
 *
 * @param {string} content - The content with OS path separators.
 * @return {string} Transformed content with updated path separators.
 */
function transformSepOfPath(content) {
  switch (os.platform()) {
    case "win32":
      return content.replace(/\\/g, "\\\\");
    default:
      return content;
  }
}

module.exports = {
  transformSepOfPath,
};

```

## Others questions

1. I wonder  how you develope or test the framework. What I do is just replace the @pareto/core: "latest" to @pareto/core:"workspace:*" in projects of examples. 
```bash
pnpm  --filter="./pacakges/core" run dev.  # to generate dist files.
pnpm install  # to install the dependencies
pnpm  --filter="./examples/tailwind" run dev 
```
2. I wonder why you develope in mix in js and ts. why not develope fully in typescript?

**Comment by Giuliao** [comment]
fix: star app failed while in windows env #6

**Comment by childrentime** [comment]
I apologize for the late response. Thank you for the changes related to Windows. Regarding the first question, if I were to publish the code in 'examples' as a template, I would have to use "@paretojs/core": "latest", because in my pnpm monorepo, 'latest' and 'workspace:*' have the same effect.

**Comment by childrentime** [comment]
Secondly, why mix js and ts? Undoubtedly I prefer to use ts, initially I used js for the development of the bin program because many of the initial examples of rspack used js. I will migrate to ts later if possible

**Comment by childrentime** [comment]
I'm currently working on adding i18n examples. Once this is complete, I plan to adjust the tooling to include typescript, eslint, prettier, and commitlint.

**Comment by childrentime** [comment]
feel free to feedback!

**Comment by Giuliao** [comment]
> I apologize for the late response. Thank you for the changes related to Windows. Regarding the first question, if I were to publish the code in 'examples' as a template, I would have to use "@paretojs/core": "latest", because in my pnpm monorepo, 'latest' and 'workspace:*' have the same effect.

I restored "workspace:*" to "latest",  deleted node_modules and pnpm install again. It worked!

**Comment by Giuliao** [comment]
> feel free to feedback!

Thanks for your reply! I like your project pareto. It' s so coooool~
